### ISSUE TITLE
Invalid Kernel Module

### ISSUE THREAD

**Issue by adilahmad17** [m1ghtym0/sgx-timing#1]
Hi,

I'm getting this error, when I try to load the kernel module.

`insmod: ERROR: could not insert module MSRdrv.ko: Invalid module format`

Can you please help me with this?

**Comment by m1ghtym0** [comment]
Hi,

I'm sorry but I can't reproduce your error.
Please make sure that that the kernel you are running and the installed version of kernel-headers is the same. Try to reboot and rebuild the module.
If the error still occurs, please provide further information like system-specs, kernel-version, etc.

**Comment by adilahmad17** [comment]
Hi,

I still have the problem. 
I'm running Ubuntu 16.04 on a Lenovo Thinkpad.

Kernel version:
`4.8.0-49-generic`

Makefile:
`KERNELDIR := /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

obj-m := MSRdrv.o

default:
  $(MAKE) -C $(KERNELDIR) SUBDIRS=$(PWD) modules

clean:
  rm -f .MSRdrv.*
  rm -f -r .tmp_versions
  rm -f *~
  rm -f MSRdrv.ko
  rm -f MSRdrv.o
  rm -f MSRdrv.mod.*
  rm -f linux.mdl
  rm -f Modules.symvers
`

System Specs:
`    description: Notebook
    product: 20FBCTO1WW (LENOVO_MT_20FB_BU_Think_FM_ThinkPad X1 Carbon 4th)
    vendor: LENOVO
    version: ThinkPad X1 Carbon 4th
    serial: R90LZHLM
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 vsyscall32
    configuration: administrator_password=disabled chassis=notebook family=ThinkPad X1 Carbon 4th power-on_password=disabled sku=LENOVO_MT_20FB_BU_Think_FM_ThinkPad X1 Carbon 4th uuid=CCAB023D-EC20-B211-A85C-CFF27D23F85C

  *-core
       description: Motherboard
       product: 20FBCTO1WW
       vendor: LENOVO
       physical id: 0
       version: SDK0J40709 WIN
       serial: W1KS6AX11ZE
       slot: Not Available

     *-cache:0
          description: L1 cache
          physical id: 3
          slot: L1 Cache
          size: 64KiB
          capacity: 64KiB
          capabilities: synchronous internal write-back data
          configuration: level=1

     *-cache:1
          description: L1 cache
          physical id: 4
          slot: L1 Cache
          size: 64KiB
          capacity: 64KiB
          capabilities: synchronous internal write-back instruction
          configuration: level=1

     *-cache:2
          description: L2 cache
          physical id: 5
          slot: L2 Cache
          size: 512KiB
          capacity: 512KiB
          capabilities: synchronous internal write-back unified
          configuration: level=2

     *-cache:3
          description: L3 cache
          physical id: 6
          slot: L3 Cache
          size: 4MiB
          capacity: 4MiB
          capabilities: synchronous internal write-back unified
          configuration: level=3

     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
          vendor: Intel Corp.
          physical id: 7
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
          serial: None
          slot: U3E1
          size: 3306MHz
          capacity: 4005MHz
          width: 64 bits
          clock: 100MHz
          
capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp cpufreq
          configuration: cores=2 enabledcores=2 threads=4
`

**Comment by m1ghtym0** [comment]
Ok there seems to be a missmatch between your kernel version and the header files.
Please provide the output of `modinfo MSRdrv.ko` and check that `vermagic:` matches
the output of `uname -r`.  You can also look into `dmesg`, after the insertion failed and provide the error message.
I hope we will find the problem, but I'm afraid the error is based on a linux-header conflict of your system.

**Comment by adilahmad17** [comment]
Here is the output:
`license:        GPL
srcversion:     C3E2FDD50478800B3CBE868
depends:        
vermagic:       4.8.0-49-generic SMP mod_unload modversions`

It matches my uname -r. Ah, so if it is based on the linux-header conflict, what would you recommend?

There is no error on dmesg, which is weird.

**Comment by adilahmad17** [comment]
Interestingly, if I remove the -f option in insmod, it installs. And lsmod also shows that the module has been loaded. However, this is the result that pmctest shows:

`Start Counters

Cannot make counter 1. No matching counter definition found

Cannot make counter 2. No matching counter definition found

Cannot make counter 3. No matching counter definition found

Cannot make counter 4. No matching counter definition found

Enabled 0 counters in each of 4 CPU cores

PMC number:   Counter name:`

**Comment by m1ghtym0** [comment]
Good, that means the Kernelmodule has been loaded. The second problem however seems weird,
as it is not connected with the module. Do you execute the `setup.sh` script? This error should only occur
if the counter-ids you entered together with the `startcounters` command are not valid.

**Comment by adilahmad17** [comment]
Thanks for the spontaneous replies! :) Yes, I used the setup.sh script. 

Here's the command:
`
12 ./pmctest startcounters 1 9 100 311
`

Are those last parameters CPU specific?

**Comment by adilahmad17** [comment]
I tried this on another computer (having similar CPU to the one you guys mention in the paper) and it works fine. It's probably something to do with the CPU and its MSRs. I'll see if I can fix this on my own PC. Thanks a lot for the help though! :)

Awesome work!

**Comment by m1ghtym0** [comment]
I'm glad to here that it worked! If you find the reason for this error, please let me know.
Thanks!:-)

**Comment by adilahmad17** [comment]
I definitely will. Thanks!
