### ISSUE TITLE
L3 cache miss counter

### ISSUE THREAD

**Issue by adilahmad17** [m1ghtym0/sgx-timing#2]
Hi,

Sorry for bothering you this much. I was wondering if you can help me activate L3 cache miss counter. It seems to be defined for PR_ALL but not for the SKYLAKE architecture (which is what i use). Do you know of a way to activate that?

Thanks!

**Comment by m1ghtym0** [comment]
Sorry for the late answer!
I don't think the driver I used supports the L3 cache miss counter and I am also not sure if SKYLAKE even has a L3 miss counter.
Nevertheless, Intel's official PMC repo might help you there: https://github.com/opcm/pcm

**Comment by adilahmad17** [comment]
Ah, no worries. Thanks, I found it out from the Intel Architecture Guide.
