### ISSUE TITLE
An error when running the code

### ISSUE THREAD

**Issue by Librajiayou** [m1ghtym0/sgx-timing#3]
Hello,
I'm getting this error when I running the code.
[Attacker] Creating thread
......
[Enclave] Enclave running on 4
[Enclave] Entering encryption loop
Segmentation fault (core dumped)

I ran the code yesterday and it ran successfully, but today when I tried again, it got wrong. I didn't change anything. Is there anything else I have not considered? Thank you!

**Comment by huwenao** [comment]
Hello, I have encountered the same issue. Can you please let me know how you resolved it? Thank you!
